apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # echo -n 'pblgllgs@gmail.com' | base64
  PG_USER_EMAIL: cGJsZ2xsZ3NAZ21haWwuY29t
  # echo -n 'password' | base64
  DB_PASSWORD: cGFzc3dvcmQ=